configuration:
  width: 800
  height: 800
  luminosity-label: '%lumi% fb^{-1} (13 TeV)'
  experiment: "CMS"
  extra-label: "Preliminary"
  root: "results/latest"
  luminosity: 2197.421
  luminosity-error: 0.046
  show-overflow: true
  error-fill-style: 3154
  error-fill-color: "#ee556270"
  ratio-fit-error-fill-style: 1001
  ratio-fit-error-fill-color: "#aa556270"
  ratio-fit-line-color: "#0B486B"

files:
  include: ['TT_files_DoubleMuon.yml', 'TT_files_MC.yml']

plots:
  include: ['TT_plots_MuMu.yml']

legend:
  position: [0.7, 0.6, 0.91, 0.91]

groups:
  data:
    legend: 'Data'
  tW:
    legend: 'Single Top tW'
    fill-color: '#C02942'
